omni3:
  ros__parameters:
    can_send: false
    lqr_0:
      kd: 0.0 
      kp: 0.0122 #10.0 * 20.0 / 16384.0
      outmax: 10.0
    lqr_1:
      kd: 0.0
      kp: 0.0122
      outmax: 10.0
    lqr_2:
      kd: 0.0
      kp: 0.0122
      outmax: 10.0